# This is development configuration.
# Production configuration that is shipped in the RPM package can be found in /package/obs/rmt.conf.
# You can create rmt.local.yml to override settings in this file.

database: &database
  host: localhost
  database: rmt_development
  username: rmt
  password: rmt
  adapter: mysql2
  encoding: utf8
  timeout: 5000
  pool: 5

database_development:
  <<: *database
  database: rmt_development

database_test:
  <<: *database
  database: rmt_test

scc:
  username:
  password:
  sync_systems: true

mirroring:
  mirror_src: false
  verify_rpm_checksums: false
  dedup_method: hardlink

http_client:
  verbose: false
  proxy:
  proxy_auth:
  proxy_user:
  proxy_password:

log_level:
  rails: debug
  cli: info

web_server:
  min_threads: 5
  max_threads: 5
  workers: 2
