name: RMT lint, unit + engines tests

on:
  pull_request:
    branches: [master]

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Only use 2 workers, gh actions seems to kill jobs when we use more
      max-parallel: 2
      matrix:
        # we need to test the Ruby versions of the products we release RMT for,
        # those are: SLE15 (2.5.8, 2.5.9), Leap 15.4 (3.0)
        ruby-version: ['2.5.8', '2.5.9', '2.7.6', '3.0.3']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: rmt_test
          MYSQL_USER: rmt
          MYSQL_PASSWORD: rmt
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: "Cache gems"
        uses: actions/cache@v3
        id: gem-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup files
        run: |
          sudo mkdir -p /var/lib/rmt
          ruby -e "require 'yaml'; puts({'database_test'=>{'host' => '127.0.0.1', 'port' => 3306, 'username'=>'rmt','password'=>'rmt','database'=>'rmt_test','adapter'=>'mysql2','encoding'=>'utf8','timeout'=>5000,'pool'=>5}}.to_yaml)" > config/rmt.local.yml
          gem env
          bundler_version=$(bundler -v | cut -d ' ' -f 3)
          echo "Ruby version: $(ruby -v)"
          echo "Available bundler: $(gem list | grep bundler)"
          # dropping default bundler setting
          rm /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/specifications/default/bundler-*.gemspec
          echo "Available bundler: $(gem list | grep bundler)"
          bundler -v
          # replacing bundler version in Gemfile.lock (BUNDLED WITH), so it works with the installed default bundler
          echo "Setting 'BUNDLED WITH' to $bundler_version in Gemfile.lock"
          sed -i "s/1.17.3/$bundler_version/g" Gemfile.lock

      - name: Run Lint
        run: |
          bundle exec rubocop -D

      - name: Prepare database
        run: |
          bundle exec rails db:migrate

      - name: Run core tests
        run: |
          bundle exec rspec --format documentation

      - name: Run PubCloud engines tests
        run: |
          bundle exec rake test:engines

      - name: Run version checks
        run: |
          echo "::group::Version verification checks"
          ruby integration/ci_check.rb
          echo "::endgroup::"
